---
- name: Распаковка архива
  unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.7.28/containerd-1.7.28-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Скачивание ситем юнит
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /etc/systemd/system/containerd.service
    mode: '755'

- name: Включить два дополнительных модуля ядра
  ansible.builtin.copy:
    src: k8sm.conf     
    dest: /etc/modules-load.d/k8s.conf
    mode: '0644'

- name: Загрузить модули overlay и br_netfilter
  ansible.builtin.shell: |
    modprobe overlay
    modprobe br_netfilter
  args:
    executable: /bin/bash

- name: форвард пакетов между интерфейсами
  ansible.builtin.copy:
    src: k8sn.conf     
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'

- name: Применить настройки sysctl
  ansible.builtin.shell: sysctl --system
  args:
    executable: /bin/bash

- name: Скачивание runc
  ansible.builtin.get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.3.0/runc.amd64
    dest: /usr/local/sbin/runc
    mode: '755'

- name: базовый config.toml 
  ansible.builtin.shell: | 
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml 
  args:
    executable: /bin/bash

- name: Включить systemd как cgroup-драйвер в config.toml
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'
  
- name: запустить containerd
  ansible.builtin.shell: |
    mkdir -p /opt/cni/bin
    systemctl daemon-reload
    systemctl enable --now containerd
  args:
    executable: /bin/bash

- name: Распаковка архива 2
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v1.7.1/cni-plugins-linux-amd64-v1.7.1.tgz
    dest: /opt/cni/bin
    remote_src: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - ubuntu-keyring
      - gpg
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    executable: /bin/bash

- name: Add Kubernetes GPG key
  ansible.builtin.shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: автозвгрузка
  ansible.builtin.shell: |
    systemctl enable --now kubelet
    sudo apt-mark hold kubelet kubeadm kubectl
  args:
    executable: /bin/bash

- name: Применить onu к кластеру
  ansible.builtin.shell: "{{ kubeadm_join }}"
  args:
    executable: /bin/bash