namespace: niopt      
name: klaster         
version: 1.0.0
readme: README.md            
authors:
  - "Niopt"
description: "Kubernetes cluster deployment using kubeadm | Joins the existing Kubernetes cluster using the provided kubeadm join command"
license: MIT
repository: "https://github.com/Niopt/kubedm_auto.git"